apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v5l3dp1uf-python
  janus-idp.io/tekton: v5l3dp1uf-python
  backstage.io/kubernetes-id: v5l3dp1uf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v5l3dp1uf-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
