apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v5l3dp1uf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v5l3dp1uf-python 
  name: v5l3dp1uf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v5l3dp1uf-python 
